whole = int(input("Enter whole number:  "))
print(whole)
decimal = float(input("Enter a whole number with a decimal portion:  "))
print(decimal)
boolean = bool(input("Enter True or False exactly!:  "))
print(boolean)
string = str(input("Enter a sentence.:  "))
print(string)
print("This is a whole number: ", whole)
print("This is a fraction shown in decimal format: ", decimal)
print("This is a boolean: ", boolean)
print("And this is a string!: +", string)
print("Program Completed!")
input("Press Enter to close the program.")
